version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - '3307:3306'
    command:
      [
        'mysqld',
        '--character-set-server=latin1',
        '--collation-server=latin1_swedish_ci',
      ]
